20181632.obj : error LNK2019: _mysql_errno@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_error@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_init@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_real_connect@32_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_select_db@8_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_query@8_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_store_result@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_free_result@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_fetch_row@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181632.obj : error LNK2019: _mysql_close@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
C:\Program Files\MySQL\MYSQL Server 8.0\lib\libmysql.lib : warning LNK4272: 'x64' 라이브러리 컴퓨터 종류가 'x86' 대상 컴퓨터 종류와 충돌합니다.
C:\Users\User\Desktop\학교\3학년 1학기\데이터베이스\prj2\20181632\20181632\Debug\20181632.exe : fatal error LNK1120: 10개의 확인할 수 없는 외부 참조입니다.
